### ISSUE TITLE
Pre-trained weights on RadNet-X

### ISSUE THREAD

**Issue by Nyquixt** [TIO-IKIM/Transfer-learning-across-domain-boundaries#1]
Hi,

Amazing work! May I ask where I could download the pre-trained weights on RadNet-X as mentioned in the paper? TIA

-K

**Comment by FJonske** [comment]
I am uploading the model weights to a publicly accessible storage platform at this very moment. The pretrained weights and the finetuned weights of experiment 1 are already in there, the rest are currently uploading (a very time-intensive process, because the machine I trained on is inside the hospital network for data privacy reasons, and has a *terrible* connection to the wider internet).

You can find them here: https://cloud.uk-essen.de/d/86d2be31e9b84d21bd5c/

Sorry for replying so late, the issue didn't reach my E-Mails for some reason. If you encounter any trouble, let me know.

**Comment by Nyquixt** [comment]
Thanks a lot!
